### PR TITLE
Fixed handling of minOrrurs of elements with @ref inside of choice

### PR DESCRIPTION
**Pull request by spilikin**
Hi,

when handling the XSD with referenced elements inside of choice the min_occurs was set to 1 and led to parsing errors. Since the code 
'''
            if parent.tag == tags.choice:
                min_occurs = 0
'''

was executed AFTER the element reference was resolved, the parent tag was always "schema" and never "choice". I moved the mic_occurs to the place where it is executed before the reference is resolved.

I hope the FIX is right and you can accept the Pull Request.

Cheers

### CODE REVIEW

**Comment by mvantellingen** [comment]
Cool, Thanks. Are you able to add  a unittest?

**Comment by mvantellingen** [comment]
Cool, Thanks. Are you able to add  a unittest?

**Comment by spilikin** [comment]
Sure, will make one and pull again

**Comment by spilikin** [comment]
unit tests are in.

**Pull request merged**
