### PR TITLE
Fill timestamp

### PR DESCRIPTION
**Pull request by tpazderka**
Fill timestamp with `Created` and `Expires` elements.

### CODE REVIEW

**Comment by mvantellingen** [comment]
Could you add a unittest? And why exactly 5 minutes as ttl?

**Comment by tpazderka** [comment]
Sure, I will add unittests. 5 minutes was my first ide, we can probable set the default ot 1 hour and leave it configurable through `Settings` object?

**Comment by mvantellingen** [comment]
I think the expires value should be a setting. A default of 5 minutes or 60 minutes is fine by me

**Comment by mvantellingen** [comment]
Wondering how this compares to #817

**Comment by tpazderka** [comment]
In #817 the Timestamp token has to be created explicitely outside the call. This tales care of that in the code.

**Comment by mvantellingen** [comment]
So I just merged #950 since that seemed sane, but then looked at this again.
Perhaps a proper solution is adding a kwarg to `Signature` like `Signature(timestamp=True)` ?

**Comment by tpazderka** [comment]
I agree that #950 looks sane. I do believe that the timestamp should be signed if present so probably no changes needed?

**Pull request closed without merging**
