### PR TITLE
Accept strings for xsd.DateTime objects

### PR DESCRIPTION
**Pull request by arturgspb**
Add check for DateTime as in Date and Time

### CODE REVIEW

**Comment by mvantellingen** [comment]
thanks

**Comment by arturgspb** [comment]
@mvantellingen 

Good! Tell me when is the next release planned?

**Comment by arturgspb** [comment]
@mvantellingen I think you may close issue https://github.com/mvantellingen/python-zeep/issues/395

**Comment by arturgspb** [comment]
@mvantellingen ping

**Pull request merged**
