### PR TITLE
fix SOAP Header namespace for SOAP 1.2

### PR DESCRIPTION
**Pull request by vashek**
Also apparently relevant for issue 92 (ws-addressing)

### CODE REVIEW

**Comment by csinchok** [comment]
Would love to see this get merged, I've been running into this issue as well.

**Comment by jeffrand** [comment]
Ditto what @csinchok said, I currently have a work around but I would much rather use this solution.

**Comment by mvantellingen** [comment]
Thanks @vashek, so I'm going to do some work on this before I can merge it (unittest, and i'm not really happy with the import statement). I'll try to look at it this weekend.

**Comment by vashek** [comment]
@mvantellingen Right, I'm not surprised. The import was there just for the assert anyway, so I removed both. And I added a unittest by basically copying and slightly modifying the one for SOAP 1.1. It does fail before the fix and succeed after it.

**Comment by mvantellingen** [comment]
@vashek thanks again. really appreciated! 👍

**Pull request merged**
