### PR TITLE
Add try catch block when accessing node.getchildren()[0]

### PR DESCRIPTION
**Pull request by andrewserong**
I ran into an `IndexError: list index out of range` with a fairly complex WSDL that I don't have any control over. Adding this check got it working for me.

### CODE REVIEW

**Comment by bfontaine** [comment]
You should check the length of `node.getchildren()` instead. If it’s empty then no need to try to access `[0]` and catch an exception.

**Comment by andrewserong** [comment]
@bfontaine thanks for the tip! I've updated the PR.

**Comment by mvantellingen** [comment]
Thanks @andrewserong! Are you also able to add an unittest for this?

**Comment by andrewserong** [comment]
Hi @mvantellingen - apologies for the delay, have added a unit test for this particular issue.

**Comment by mvantellingen** [comment]
Thanks!!

**Pull request merged**
