### PR TITLE
adds support for checking if abstract message is None

### PR DESCRIPTION
**Pull request by passion4code**
Helps with sloppy WSDLs :)

### CODE REVIEW

**Comment by passion4code** [comment]
@mvantellingen I'm not sure why the AppVeyor Python 3.3 build is failing (seems to be happening for all recent PRs against your repo)

Looking forward to any feedback, as this change is critical for a project my team is working on.

**Comment by mvantellingen** [comment]
Could you at a unittest?

**Comment by passion4code** [comment]
@mvantellingen This has been done. Thanks for the feedback. 

Test passes. 

If you run the test with `src/zeep/wsdl/messages/soap.py:282` changed to it's original:

```
if not abstract_message.parts and self.type != 'input':
```

The test fails, as expected.

**Comment by mvantellingen** [comment]
Thanks. I've merged it without the version updates

**Pull request closed without merging**
