### PR TITLE
wsse verify fix

### PR DESCRIPTION
**Pull request by csotomon**
Added wsee list verify code when using UsernameToken and Signature together.

### CODE REVIEW

**Comment by mvantellingen** [comment]
Could you at a unittest?

**Comment by csotomon** [comment]
I added the test script

**Comment by mvantellingen** [comment]
It fails :-)

**Comment by csotomon** [comment]
Hi @mvantellingen, the problem is with the xmlsec signature verification and not with the fix, i don't know how to creare a valid signed message.  Can you help me with that?

**Comment by csotomon** [comment]
@mvantellingen do you have some news about this pull request?

**Comment by csotomon** [comment]
@mvantellingen are U thinking in accept this request?

**Comment by jlcasasg** [comment]
+1

**Comment by juansgaitan** [comment]
+1

**Comment by csotomon** [comment]
I think that @mvantellingen is not interested un merge this fix

**Comment by mvantellingen** [comment]
The reason i haven’t merged this yet is because the tests fail

**Comment by csotomon** [comment]
I don't know how to Builes a good testimg code, and i don't have a public wsse endpoint to test it.

**Comment by anna-anisienia** [comment]
+1 same issue

client.wsse.verify(doc)
AttributeError: 'list' object has no attribute 'verify'

**Pull request closed without merging**
