### PR TITLE
Allow disabling SSL certificates verification

### PR DESCRIPTION
**Pull request by onjin**
Hi. It would be nice to have control over all `requests` params, but so far I cannot use `zeep` because of SSL verification.

### CODE REVIEW

**Comment by mvantellingen** [comment]
hi @onjin, thanks for the PR! 

The changes to the transport module look good, but I'm not sure about the `verify` kwarg in `client.Client()`. 

I see one of the following options:

```
    client = zeep.Client(wsdl, transport_options={'verify': False, 'timeout': 600})
```

Or the more explicit:
```
    transport = zeep.transport.Transport(verify=False, timeout=600)
    client = zeep.Client(wsdl, transport=transport)
```

But you opinion is more then welcome 👍

**Comment by onjin** [comment]
hi @mvantellingen 

explicit versions looks good, but then should we move `cache` option from `Client` to `Transport`?

    transport = zeep.transports.Transport(verify=False, timeout=600, cache=None)
    client = zeep.Client(wsdl, transport=transport)

    class Transport(object):
        def __init__(self, cache=None, timeout=300, verify=True):
            self.cache = cache or SqliteCache()

**Comment by mvantellingen** [comment]
Yeah, agree. The cache is currently only used within the transport layer. My initial thinking was to use it for the parsed wsdl state, but in practice the parsing is fast enough to skip caching here.

**Comment by onjin** [comment]
I removed `cache` option from `Client` because it's still `dev` release. But i can make it backward compatible with deprecation warning if we need that.

**Comment by mvantellingen** [comment]
Thanks! Can you also update the __main__ module? I've just added a unittest for it on the master branch. 

Regarding the deprecation warning, I think we can skip it indeed. After the 1.0 release (which shouldn't take too long) we should aim for good semver practices.

**Comment by onjin** [comment]
Sure. `__main__` updated and pushed.

**Comment by mvantellingen** [comment]
Thanks ! :D

**Pull request merged**
