### PR TITLE
Fix helpers.serialize_object

### PR DESCRIPTION
**Pull request by YAmikep**
- Fix helpers.serialize_object for lists of ints (#123).
 - Allow to change the dict type used in helpers.serialize_object.

### CODE REVIEW

**Comment by mvantellingen** [comment]
I've just refactored the helpers.serialize_object() and now this should work.

**Comment by YAmikep** [comment]
@mvantellingen You did not want to keep the `dict_type` parameter? It would be handy.

**Comment by mvantellingen** [comment]
Maybe, what is exactly the use-case for it?

**Comment by YAmikep** [comment]
The type of dict returned is currently hard coded in the function: `OrderedDict`.
I'd like to get simple dicts instead.
Having a parameter would at least give the option to change the type of object to use.

**Comment by mvantellingen** [comment]
I understand, and although the change is pretty easy i'm more interested in the idea behind it. Is it required for json or something else?

**Comment by YAmikep** [comment]
Yes, I store the output as json later on and was having issues with an OrderedDict.
Also, an OrderedDict is less efficient and if we do not need to keep the order, we might as well use a simpler dict.
Anyways, I think having at least the option is better as the user can make his own decision regarding the type to use.

**Comment by mvantellingen** [comment]
Okay fine ;-)

It's in master

**Comment by YAmikep** [comment]
Cool thanks. 
FYI, I added a comment in the commit: you need to pass the parameter to the function in the recursive calls as wel..

**Pull request closed without merging**
