### PR TITLE
fix data type date parsing

### PR DESCRIPTION
**Pull request by frNNcs**

### CODE REVIEW

**Comment by leranp** [comment]
it fix my problem , thanks

**Comment by mvantellingen** [comment]
I think only the `import` change is needed right?

**Comment by frNNcs** [comment]
I remove the line
``` python
if len(value) == 10:
    value += "T00:00:00"
elif (len(value) == 19 or len(value) == 26) and value[10] == " ":
    value = "T".join(value.split(" "))
```
too, that conflicted with the date parsing

**Comment by mvantellingen** [comment]
This PR is way to vague, no clear idea what it solves

**Pull request closed without merging**
