### PR TITLE
Fix compatability with aiohttp>=3

### PR DESCRIPTION
**Pull request by atx**
Note that this might be a breaking change - not sure what your policy is on that.

### CODE REVIEW

**Comment by decaz** [comment]
@atx can you make some fixes so tests will pass?

**Comment by atx** [comment]
Oops, completely forgot about this - fixed.

The remaning test failures seem to be [caused](https://github.com/jupyter/notebook/issues/3397) by Tornado 5.0 (testing with 4.5.3 works).

**Comment by vdboor** [comment]
@atx is there any advantage of specifying the timeout over what I've done in PR #735?

**Comment by atx** [comment]
I don't think there is. aiohttp itself does some [more complicated stuff](https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L181) with its timeout code but it's not obvious to me if it really matters.

**Comment by mvantellingen** [comment]
I think this was a duplicate with #735 right? I've merged that one before reviewing this one (sorry)

**Comment by dirkmb** [comment]
besides the fact that #735 missed to change the `get`-method of `AsyncTransport`, which still uses `aiohttp.Timeout`

**Pull request closed without merging**
