### PR TITLE
fix(QName): return QName for `anyType` when given xsd string ""

### PR DESCRIPTION
**Pull request by nicholasli137**
Implements mvantellingen/python-zeep#349

### CODE REVIEW

**Comment by mvantellingen** [comment]
Thanks! Are you able to add a unittest?

**Comment by nicholasli137** [comment]
Sure, I will add a unit test for my change.

**Comment by nicholasli137** [comment]
oh my god, there is no documentation for the contributing.

**Comment by mvantellingen** [comment]
Oh my god!! Panic!! :-)

Really, it's just something i haven't found time for. PR's welcome.
Basically, do checkout, create virtualenv, run ``make install test`` and there it is.

**Comment by mvantellingen** [comment]
Fixed in 1.1.0

**Comment by nicholasli137** [comment]
Thank you so much Michael!

**Pull request closed without merging**
