### PR TITLE
No longer using defusedxml since it is not necessary.

### LINKED ISSUE #956: DeprecationWarning: defusedxml.lxml is no longer supported
`zeep/loader.py` imports `defusedxml.lxml.fromstring`, this works, but was (recently) deprecated:

```
DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
```

The best references to why it was deprecated I could find are here:

https://github.com/tiran/defusedxml/issues/31
https://github.com/tiran/defusedxml/issues/25

### LINKED ISSUE #1014: pytest - zeep - DeprecationWarning : defusedxml.lxml is no longer supported and will be removed in a future release
Python 3.7.4
Pytest 5.2.1
Zeep 3.2

code to reproduce

```
from zeep import Client

def test_number_to_words():
    client = Client('http://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL')
    assert client.service.NumberToWords(100) == "one hundred "

```

on execution result

```
============================== warnings summary ===============================
C:\Users\andreabisello\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zeep\loader.py:3
  C:\Users\andreabisello\AppData\Local\Programs\Python\Python37-32\lib\site-packages\zeep\loader.py:3: DeprecationWarning: defusedxml.lxml is no longer supported and will be removed in a future release.
    from defusedxml.lxml import fromstring

-- Docs: https://docs.pytest.org/en/latest/warnings.html

```

the warning looks related to pytest, but about zeep.

due i want to use pytest and zeep in production environment, should i move to another test framework or another soap library?

thanks.

### PR DESCRIPTION
**Pull request by klaasjanelzinga**
Closes #956 
Closes #1014 

It is not necessary to use defused when using the lxml parser. The package defusedxml.lxml is deprecated because of this. 

The lxml parser uses libxml2 that has the guards against the vulnerabilities build in (at least  libxml2 > 2.6). Since zeep already uses the lxml parser, this pull request removes defusedxml as a dependency. Some functionality regarding `forbid_dtd` and `forbid_entities` that were present in defusedxml is now present in `loader.py` and exceptions were added to zeep with the same name as in defusedxml.

- dependency on defusedxml removed
- added two new exception classes `DTDForbidden` en `EntitiesForbidden`
- when loading a document the docinfo is checked for entities and doctype.

### CODE REVIEW

**Comment by klaasjanelzinga** [comment]
Zie blurb on https://github.com/tiran/defusedxml/blob/master/defusedxml/lxml.py for an explanation:

> """DEPRECATED Example code for lxml.etree protection
> The code has NO protection against decompression bombs.
> """

**Comment by Yanonix** [comment]
Have you an estimate date for a new release with this pull request ?
Thanks

**Comment by klaasjanelzinga** [comment]
I do not know, I haven't had any feedback on this PR from the owner. The repository seems very quiet.

**Comment by mvantellingen** [comment]
Looks good, thanks! This was on my todo list for a while

**Pull request merged**
