### PR TITLE
Make SOAP operation arguments available in Plugin.egress

### PR DESCRIPTION
**Pull request by ri8on**

### CODE REVIEW

**Comment by mvantellingen** [comment]
Thanks! I think we want to encapsulate the args/kwargs or accept them as op_args / op_kwargs and not unpack them. Since now might error when the operation accepts a kwarg operation :-)

**Comment by ri8on** [comment]
Yeah, you're right, it's my oversight )

**Comment by mvantellingen** [comment]
Thanks. I'll need to add some code to make it backwards compatible but that should be doable. I'll look at it asap

**Comment by ri8on** [comment]
Thanks!

**Comment by vstoykov** [comment]
@ri8on your PR need to be rebased against master. Can you do that?

**Pull request closed without merging**
